# Docs for the Azure Web Apps Deploy action:
# https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure:
# https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - Hotel-Management-System-Udit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore dependencies
        run: dotnet restore CozyHavenStayServer/CozyHavenStayServer.csproj

      - name: Build with dotnet
        run: dotnet build CozyHavenStayServer/CozyHavenStayServer.csproj --configuration Release --no-restore

      - name: Publish with dotnet
        run: dotnet publish CozyHavenStayServer/CozyHavenStayServer.csproj --configuration Release -o "${{env.DOTNET_ROOT}}/myapp" --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4458320D1C53424D89C24D7D1FEF3102 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FE1315B841784961B32A9461E81B227B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D47ACB5BA9CC4EDFBF7520B070B42801 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Hotel-Management-System-Udit'
          slot-name: 'Production'
          package: .
